### ISSUE TITLE
Device not found

### ISSUE THREAD

**Issue by kalashluvr** [apollo1220/blueprints#9]
Hi - I've imported the blueprint, and my aqara wirless mini switch is showing as a device in HA, but the blueprint isn't finding the device to be available.  Any thoughts how to fix?

**Comment by apollo1220** [comment]
The blueprint only supports through ZHA. If it is added to HA via something else like zigbee2mqtt it won't be found or work.

**Comment by alexbergsland** [comment]
> Hi - I've imported the blueprint, and my aqara wirless mini switch is showing as a device in HA, but the blueprint isn't finding the device to be available. Any thoughts how to fix?

Try this one:
https://github.com/AramidX/ha-blueprint/blob/main/blueprints/sonoff/sonoff_snzb01_wireless_switch_z2m.yaml
